### PR TITLE
Feature gatsby image

### PR DESCRIPTION
**Pull request by LukeSchlangen**
Not ready to merge, just hoping to trigger Netlify build

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
The biggest goal of this branch was to improve the lighthouse scores. This branch does that, although from a styling perspective, it sets us back a bit. The biggest step backwards was that icons were a performance issue, so those have been removed until we convert them to `svg`s, which I don't think needs to be done before deployment. However, we will need to add padding. The good news is, this is really huge for our lighthouse scores, which is the main point of this conversion.

@ivers598, I know you put a lot of work into the icons, so I want to appologize that they are not included in the current build, but wanted to let you know that I plan to add them back. 

screen shot 2018-09-03 at 10 04 37 am

**Comment by madiemm97** [comment]
The images aren't centered for me, are they supposed to be? A lot of the style/coloring also changed. Such as the buttons are now dark blue. 
image
image

**Comment by LukeSchlangen** [comment]
@madiemm97 I tried to brighten the buttons a little bit, but the standards seem pretty strict according to https://webaim.org/resources/contrastchecker/ It might be worth digging into accessibility guidelines elsewhere, since this seems pretty limiting. Looking at lighthouse though, this increase in brightness seems to comply with its standards for accessiblity.

The images should now always be 100% width, which might not be great on very large screens since it will start to stretch the image noticeably with bad image quality?

**Comment by LukeSchlangen** [comment]
@madiemm97 I didn't change the header image. It still has color (although it definitely doesn't look like it). I do think it would be good to change out those images within a few days of deploying them.

I'll merge this in!

**Pull request merged**
