### PR TITLE
Added sitemap.xml

### PR DESCRIPTION
**Pull request by yongzhihuang**
Added Sitemap, but I have a a suggestion, 

- This sitemap should be rendered via a server rendered language, so the date can appear dynamic rather than hardcoded.

### CODE REVIEW

**Comment by yongzhihuang** [comment]
for issue #8

**Comment by LukeSchlangen** [comment]
Thank you! I'm currently hosting the site for free as a static site and would prefer not to pay for a server or include the additional complexity of a server just for the purpose of keeping the date dynamic, but if there is a way to do it without the overhead of a server, I'd definitely be interested.

**Comment by yongzhihuang** [comment]
If you have PHP available (most free hostings do), then you can use a library like this: https://github.com/icamys/php-sitemap-generator

**Comment by LukeSchlangen** [comment]
Thanks! We are hosting the static site directly from Github, so I think it might be a little trickier than that. I'll leave it alone for now, but keep this in mind if we ever add a server. Thanks!

**Pull request merged**
