### PR TITLE
add search functionality to classes - imperfect

### PR DESCRIPTION
**Pull request by ivers598**
Not perfect. The search correctly search through the startdate, enddate, time, and grade columns; however, for the className, district, and days column seems to be searching starting from the middle of the word.

### CODE REVIEW

**Comment by LukeSchlangen** [comment]
In a table, the only allowed child element directly within a `<tr>` is a `<td>` so instead, the link must be within each `<td>`. (The worst, because it's so repetitive.) We could make a component specifically to to this, but probably not worth it at this point.

**Comment by ivers598** [comment]
For example, when typing "Os" for Osseo, is brings up only the "os" part in Rosemount.

image

**Comment by LukeSchlangen** [comment]
Got it. It’s because it’s looking for an exact string match (the capital O in Osseo doesn’t match the lowercase os in your search).

So that should be something doable in the filter function with a .toLowerCase on the string and the substring.

The next question is do we want rosemount to show up at all when typing “os” we definitely want “video game creation” to show up if we type “game” so I think for now, we leave matches in the middle of strings.

Is the .toLowercase something you want to try fixing?

**Comment by ivers598** [comment]
What a simple thing for me to forget (especially since we teach this to the kids in class). Correction is made and it works correctly! Not the prettiest table; however, I'm pretty sure that isn't the point.

**Comment by LukeSchlangen** [comment]
Great! Did you commit and push those changes? (I’m not seeing the toLowerCase code on github)

**Comment by ivers598** [comment]
For some reason, pushing is giving me an error. Created a new branch with correct code and closing this request.

**Pull request closed without merging**
