### PR TITLE
convert the current site to gatsby

### PR DESCRIPTION
**Pull request by swoollums**

### CODE REVIEW

**Comment by swoollums** [comment]
Whoops! I dont know what that is and I dont know how it got deleted! I re-added it by copy and paste so I hope it works!

**Comment by LukeSchlangen** [comment]
@swoollums The H1 is there, and the scrolling technically goes to the right spot, but they are hidden now because of the floating nav bar. For how much work it is, I think it makes sense to remove the floating nav bar if it's that much work. I'll let you decide Sam if you want to remove the floating nav bar or add spacing and padding to make sure that the `H1` displays.

**Comment by LukeSchlangen** [comment]
I think we can leave the footer in here too. Seems like it was removed? It's not on the current site, but I think it's a good addition seo-wise

**Comment by LukeSchlangen** [comment]
@ivers598 I think the build is breaking, but I don't think Sam's recent changes would have caused that? My build is also breaking locally. I think your latest changes to the spreadsheet may be causing breaking builds for everyone?

**Pull request merged**
